#!/bin/bash
# This is an extremely kludgy test launcher which runs the standard Redis
# test suite against Karton. The goal is kinda make the test suite complete
# without crashing; then we can work on making the 1.0 release.

# Install fake redis-server executable. For now, it takes care of parsing
# the Redis config, extracting important bits of information and passing
# them as command line arguments to twisted_karton.
ln -sfn $PWD/tests/redis-server-wrapper redis/src/redis-server

# Fix PING testing logic. Karton doesn't support line-based protocol yet.
sed -e 's/"PING\\r\\n"/"*1\\r\\n\\$4\\r\\nPING\\r\\n"/' \
    -i'~' redis/tests/support/server.tcl

# Bypass assert_encoding since we don't have any.
sed -e 's/\(proc assert_encoding.*{\).*/\1 return/' \
    -i'~' redis/tests/support/test.tcl

cd redis

run_test() {
    echo $'\x1b[0;1;33m'"Running test suite: $1"$'\x1b[0m'
    ./runtest --clients 1 --single "$1"
}

# Run the test suites. Good luck.
if [[ "$#" != 0 ]]; then
    for testpath in "$@"; do
        run_test "$testpath"
    done
else
    run_test unit/auth
    run_test unit/basic
    run_test unit/type/list
    run_test unit/type/set
    run_test unit/type/zset
fi
